trigger:
  - none

pr: none

variables:
  - group: Secrets

    
pool:
  name: Azure Pipelines

jobs:
  - job: CreateBranch
    steps:
      - checkout: self
      - task: PowerShell@2
        displayName: 'Create Branch'
        inputs: 
          pwsh: true
          azurePowerShellVersion: LatestVersion
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/scripts/create-branch.ps1'
          workingDirectory: $(Build.SourcesDirectory)



