trigger:
  - none

pr: none

variables:
  - group: Secrets
  - name: githubPat
    value: $(GitHub_Token)

pool:
  name: SelfHosted


jobs:
  - job: CreateBranch
    steps:
      - checkout: self
      - task: PowerShell@2
        displayName: 'Create Branch'
        inputs: 
          pwsh: true
          azurePowerShellVersion: LatestVersion
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/scripts/create-branch.ps1'
          workingDirectory: $(Build.SourcesDirectory)
        env:
          GITHUB_PAT: $(GitHub_Token)



