trigger:
  - none

pr: none

variables:
  - group: Secrets
  userEmail: $(samsthomas@hotmail.co.uk)
  userName: $(samsthomas)

pool:
  name: SelfHosted

jobs:
  - job: CreateBranch
    steps:
      - checkout: self
        persistCredentials: true

      - script: |
          git config user.email $(userEmail)
          git config user.name $(userName)
        displayName: 'Configure Git User'
      
      - task: PowerShell@2
        displayName: 'Test GitHub API Connection'
        inputs:
          targetType: 'inline'
          script: |
            $testUri = "https://api.github.com"
            try {
              $response = Invoke-WebRequest -Uri $testUri -UseBasicParsing
              Write-Host "Connection to $testUri successful. Status code: $($response.StatusCode)"
            } catch {
              Write-Host "Failed to connect to $testUri. Error: $_"
              exit 1
            }
      
      - task: PowerShell@2
        displayName: 'Create Branch'
        inputs: 
          pwsh: true
          azurePowerShellVersion: LatestVersion
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/scripts/create-branch.ps1'
          workingDirectory: $(Build.SourcesDirectory)
        env:
          GITHUB_PAT: $(GitHub_Token)