trigger:
  - none

pr: none

parameters:
  -name: NewBranchName
    type: string
    displayName: "New Branch Name"


variables:
  - group: Secrets #This is the azure pipeline library where the PAT is stored

  - name: Enable Github Task
    value: false
  

pool:
  name: SelfHosted

jobs:
  - job: CreateBranch
    steps:
      - checkout: self
        persistCredentials: true

      
      - task: PowerShell@2
        displayName: 'Create Branch on all github repos'
        condition: eq(variables['Enable Github Task'], 'true')
        inputs: 
          pwsh: true
          azurePowerShellVersion: LatestVersion
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/scripts/mass-branch-create.ps1'
          arguments: '-newBranch "${{ parameters.NewBranchName }}"'
          workingDirectory: $(Build.SourcesDirectory)
        env:
          GITHUB_PAT: $(GitHub_Token)


      
      - task: PowerShell@2
        displayName: 'Create Branch on all ADO repos'
        continueOnError: true
        inputs: 
          pwsh: true
          azurePowerShellVersion: LatestVersion
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/scripts/mass-branch-create-ado.ps1'
          arguments: '-newBranch "${{ parameters.NewBranchName }}"'
          workingDirectory: $(Build.SourcesDirectory)
        env:
          ADO_PAT: $(ADO_Token)

      