trigger:
  - none

pr: none

variables:
  - group: Secrets #This is the azure pipeline library where the PAT is stored

  - name: Enable Github Task
    value: false
  
  # - name: userEmail
  #   value: $(samsthomas@hotmail.co.uk)
  # - name: userName
  #   value: $(samsthomas)

pool:
  name: SelfHosted

jobs:
  - job: CreateBranch
    steps:
      - checkout: self
        persistCredentials: true

      # - script: |
      #     git config user.email $(userEmail)
      #     git config user.name $(userName)
      #   displayName: 'Configure Git User'
      
      - task: PowerShell@2
        displayName: 'Create Branch on all github repos'
        condition: eq(variables['Enable Github Task'], 'true')
        inputs: 
          pwsh: true
          azurePowerShellVersion: LatestVersion
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/scripts/mass-branch-create.ps1'
          workingDirectory: $(Build.SourcesDirectory)
        env:
          GITHUB_PAT: $(GitHub_Token)
      
      - task: PowerShell@2
        displayName: 'Create Branch on all ADO repos'
        continueOnError: true
        inputs: 
          pwsh: true
          azurePowerShellVersion: LatestVersion
          targetType: filePath
          filePath: '$(Build.SourcesDirectory)/scripts/mass-branch-create-ado.ps1'
          workingDirectory: $(Build.SourcesDirectory)
        env:
          ADO_PAT: $(ADO_Token)

      