trigger: none

schedules:
  - cron: "0 7 * *"
  displayName: Daily Scan
  branches:
    include:
    - main
  always: true

variables:
- group: TeamsWebhookUrl  # Store webhook URL here

steps:
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(System.DefaultWorkingDirectory)/scripts/get-security-alerts.py'
  env:
    GITHUB_TOKEN: $(githubToken)
    TEAMS_WEBHOOK_URL: $(TeamsWebhookUrl)

