trigger: none

pool:
  name: SelfHosted

variables:
  user.email: "samsthomas@hotmail.co.uk"
  user.name: "samsthomas"

  yamlFilePath: '$(Build.SourcesDirectory)/Image-tags/key-pair.yaml'

steps:
  - checkout: self 
    persistCredentials: true

  - script: |
      git config user.email ${{variables['user.email']}}
      git config user.name ${{variables['user.name']}}
    displayName: 'configure git creds'

  - task: PowerShell@2
    displayName: "Create Latest tag for releases"
    inputs:
      pwsh: true
      azurePowerShellVersion: latestVersion
      targetType: 'filePath'
      filePath: $(Build.SourcesDirectory)/Auto-tagging/powershell-scripts/set-release-tag.ps1
      workingDirectory: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Update Tag Folder
    inputs:
      targetType: 'inline'
      script: |

        Write-Host "Current directory: $(Get-Location)"
        Write-Host "YAML file path: $(yamlFilePath)"
        
        # Configure git
        git config user.email ${{variables['user.email']}}
        git config user.name ${{variables['user.name']}}
        
        # Fetch latest changes
        git fetch origin main
        
        # Create a fresh branch from origin/main
        $branchName = "update-yaml-$(Build.BuildNumber)"
        git checkout -b $branchName origin/main
        
        # Update YAML file
        Import-Module powershell-yaml
        Write-Host "Updating YAML file..."
        $content = Get-Content -Path "$(yamlFilePath)" -Raw
        Write-Host "Current YAML content:"
        Write-Host $content
        
        $versionsYaml = ConvertFrom-Yaml $content
        # Ensure we maintain the variables structure
        if (-not $versionsYaml.variables) {
            $versionsYaml.variables = @{}
        }

        $versionsYaml.variables.key = "$(Build.BuildNumber)"
        $newContent = ConvertTo-Yaml $versionsYaml
        $newContent | Set-Content -Path "$(yamlFilePath)"
        
        Write-Host "New YAML content:"
        Get-Content -Path "$(yamlFilePath)"

        git status --porcelain
        
        # Commit and push changes
        git add "$(yamlFilePath)"
        git commit -m "Updated key value pair to $(Build.BuildNumber)"
        
        # Push directly to main without branch reference
        git push origin HEAD:main --force
        
        





