trigger: none

pool:
  name: SelfHosted

variables:
  user.email: "samsthomas@hotmail.co.uk"
  user.name: "samsthomas"
  group: Secrets

  yamlFilePath: '$(Build.SourcesDirectory)/Image-tags/key-pair.yaml'

steps:
  - checkout: self 
    persistCredentials: true

  - script: |
      git config user.email ${{variables['user.email']}}
      git config user.name ${{variables['user.name']}}
    displayName: 'configure git creds'

  - task: PowerShell@2
    displayName: "Create Latest tag for releases"
    inputs:
      pwsh: true
      azurePowerShellVersion: latestVersion
      targetType: 'filePath'
      filePath: $(Build.SourcesDirectory)/Auto-tagging/powershell-scripts/set-release-tag.ps1
      workingDirectory: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Update Tag Folder
    inputs:
      targetType: 'inline'
      script: |

        Write-Host "Current directory: $(Get-Location)"
        Write-Host "YAML file path: $(yamlFilePath)"
        
        
        # git config user.email ${{variables['user.email']}}
        # git config user.name ${{variables['user.name']}}
        
        git clone https://$env:GitHub_PAT@github.com/samsthomas/Python-GitHub-Security.git
        cd Python-GitHub-Security
        

        git branch -l
        
        git fetch origin main
        
        $branchName = "update-yaml-$(Build.BuildNumber)"
        git checkout -b $branchName origin/main

        Write-Host "Current directory: $(Get-Location)"

        Import-Module powershell-yaml

        

        $yamlFilePath = "$(Get-Location)/Image-tags/key-pair.yaml"
        Write-Host "Updated YAML file path: $yamlFilePath"

        Write-Host "Updating YAML file..."

        $content = Get-Content -Path "$(yamlFilePath)" -Raw
        Write-Host "Current YAML content:"
        Write-Host $content
        
        $versionsYaml = ConvertFrom-Yaml $content
        
        # Ensure we maintain the variables structure
        # if (-not $versionsYaml.variables) {
        #     $versionsYaml.variables = @{}
        # }

        $versionsYaml.variables.key = "$(Build.BuildNumber)"
        $newContent = ConvertTo-Yaml $versionsYaml
        $newContent | Set-Content -Path "$(yamlFilePath)"
        
        Write-Host "New YAML content:"
        Get-Content -Path "$(yamlFilePath)"

        git status --porcelain
        git add "$yamlFilePath"
        
        git commit -m "Updated key value pair to $(Build.BuildNumber)"
        
        git push origin HEAD:main --force
    env:
      GitHub_PAT: $(GitHub_Token)
        





