trigger: none

pool:
  name: SelfHosted

variables:
  user.email: "samsthomas@hotmail.co.uk"
  user.name: "samsthomas"

  yamlFilePath: '$(Build.SourcesDirectory)/Image-Tags/key-pair.yaml'

steps:
  - checkout: self 
    persistCredentials: true

  - script: |
      git config user.email ${{variables['user.email']}}
      git config user.name ${{variables['user.name']}}
    displayName: 'configure git creds'

  - task: PowerShell@2
    displayName: "Create Latest tag for releases"
    inputs:
      pwsh: true
      azurePowerShellVersion: latestVersion
      targetType: 'filePath'
      filePath: $(Build.SourcesDirectory)/Auto-tagging/powershell-scripts/set-release-tag.ps1
      workingDirectory: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Update Tag Folder
    inputs:
      targetType: 'inline'
      script: |

        Write-Host "Current directory: $(Get-Location)"
        Write-Host "YAML file path: $(yamlFilePath)"

        git config user.email ${{variables['user.email']}}
        git config user.name ${{variables['user.name']}}

        git config pull.rebase false

        git fetch origin main

        git checkout main
        git pull origin main

        Import-Module powershell-yaml

        Write-Host "Updating YAML file..."
        Write-Host " "
        Write-Host " "

        $content = Get-Content -Path "$(yamlFilePath)" -Raw
        

        Write-Host "Current YAML content:"
        Write-Host $content

        $versionsYaml = ConvertFrom-Yaml $content
        $versionsYaml.key = "$(Build.BuildNumber)"

        $newContent = ConvertTo-Yaml $versionsYaml
        $newContent | Set-Content -Path "$(yamlFilePath)"

        Get-Content -Path "$(yamlFilePath)"

        Write-Host " "
        Write-Host " "

        Write-Host "git status after changes:"

        git status

        git add "$(yamlFilePath)"

        git commit -m "updated key value pair version to x"

        git pull origin main --no-rebase

        git push origin main
        





