trigger: none

pool:
  name: SelfHosted

variables:
  user.email: "samsthomas@hotmail.co.uk"
  user.name: "samsthomas"
  group: Secrets



steps:
  - checkout: self 
    persistCredentials: true

  - script: |
      git config user.email ${{variables['user.email']}}
      git config user.name ${{variables['user.name']}}
    displayName: 'configure git creds'

  - task: PowerShell@2
    displayName: "Create Latest tag for releases"
    inputs:
      pwsh: true
      azurePowerShellVersion: latestVersion
      targetType: 'filePath'
      filePath: $(Build.SourcesDirectory)/Auto-tagging/powershell-scripts/set-release-tag.ps1
      workingDirectory: $(Build.SourcesDirectory)

  - task: PowerShell@2
    displayName: Update Tag Folder
    inputs:
      targetType: 'inline'
      script: |

        
        #pull repo
        $repoName = "https://github.com/samsthomas/Python-GitHub-Security"
        $clonePath = "$env:BUILD_SOURCESDIRECTORY/Python-GitHub-Security"

        Write-Host "Cloning Repo"

        git clone --branch main $repoName $clonePath

        cd $clonePath

        Write-Host "Current directory: $(Get-Location)"

        pwd
        
        # git config user.email ${{variables['user.email']}}
        # git config user.name ${{variables['user.name']}}
        

        # cd Python-GitHub-Security

        $yamlFilePath = "$(Get-Location)/Image-tags/key-pair.yaml"
        Write-Host "Updated YAML file path: $yamlFilePath"

        if (!(Test-Path $yamlFilePath)) {
            Write-Host "ERROR: YAML file not found at $yamlFilePath"
            exit 1
        }
        
        git branch -l
        
        git fetch origin main
        
        $branchName = "update-yaml-$(Build.BuildNumber)"
        git checkout -b $branchName origin/main

        Write-Host "Current directory: $(Get-Location)"

        Import-Module powershell-yaml

        



        Write-Host "Updating YAML file..."

        $content = Get-Content -Path "$yamlFilePath" -Raw
        Write-Host "Current YAML content:"
        Write-Host $content
        
        $versionsYaml = ConvertFrom-Yaml $content
        
        # Ensure we maintain the variables structure
        # if (-not $versionsYaml.variables) {
        #     $versionsYaml.variables = @{}
        # }

        $versionsYaml.variables.key = "$(Build.BuildNumber)"
        $newContent = ConvertTo-Yaml $versionsYaml
        $newContent | Set-Content -Path "$(yamlFilePath)"
        
        Write-Host "New YAML content:"
        Get-Content -Path "$yamlFilePath"

        git status --porcelain
        git add "$yamlFilePath"
        
        git commit -m "Updated key value pair to $(Build.BuildNumber)"
        
        git push origin HEAD:main --force
    env:
      GitHub_PAT: $(GitHub_Token)
        





